import React, { ReactNode } from 'react'
import { SessionProvider } from "next-auth/react"

import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'

import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/context/ThemeContext"
import AuthProvider from "@/components/AuthProvider/AuthProvider"
import { AppProps } from "next/app"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lama Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  pageProps
}: {
  children: ReactNode,
  pageProps: any
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
